name: "SYCL Python Interface Test"

on:
  push:
    branches: [ "sycl-develop" ]
  pull_request:
    branches: [ "sycl-develop" ]
  merge_group:
    branches: [ "sycl-develop" ]
  workflow_dispatch:
    inputs:
      DPCPP_VERSION:
        description: "DPCPP version to use"
        type: string

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Python Interface tests on Intel PVC
    # strategy:
    #   matrix:
    #     compiler: [ NIGHTLY, RELEASE ]
    runs-on: cp-gpumax-1100-gpu
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install DPC++
        id: install_dpcpp
        uses: ./.github/actions/install-dpcpp
        with:
          # DPCPP_RELEASE: ${{ matrix.compiler }}
          DPCPP_VERSION: nightly-2025-06-10
          DPCPP_PATH: ~/dpcpp
      - name: Setup virtual environment
        shell: bash
        run: |
          python3 -m venv ~/.venv
          source ~/.venv/bin/activate
          . setvars.sh
          # Persist environment variables to following steps
          env >> $GITHUB_ENV
          sycl-ls

      - name: Install DPCTL
        id: install_dpctl
        uses: ./.github/actions/install-dpctl
        with:
          DPCTL_URL: https://github.com/IntelPython/dpctl.git
          DPCTL_BRANCH: master
          DPCTL_PATH: ~/dpctl
          VENV_PATH: ~/.venv
      - name: Install Torch XPU
        shell: bash
        run: |
          source ~/.venv/bin/activate
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/xpu
          pip uninstall --yes intel-sycl-rt intel-cmplr-lib-ur umf
      - name: Run Python Interface GEMM Tests
        shell: bash
        run: |
          source ~/.venv/bin/activate
          pip install -e .
          export CUTLASS_USE_SYCL=1
          export SYCL_UR_TRACE=2
          export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
          python test/python/cutlass/gemm/run_all_tests.py
